### ISSUE TITLE
Latest version (0.2.16) not working - LangSmith API error

### ISSUE THREAD

**Issue by ronnyskog** [souzatharsis/podcastfy#135]
PS D:\Data\Software\Python\Podcastify> & d:/Data/Software/Python/Podcastify/.venv/Scripts/python.exe d:/Data/Software/Python/Podcastify/app.py
2024-10-31 19:52:45,555 - podcastfy.client - INFO - Processing 2 links
D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\client.py:221: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted LangSmith API
  warnings.warn(
Error generating content: Failed to GET /commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc in LangSmith API. HTTPError('400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc', '{"detail":"No prompt owner specified"}')
2024-10-31 19:52:51,955 - podcastfy.client - ERROR - An error occurred in the process_content function: Failed to GET /commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc in LangSmith API. HTTPError('400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc', '{"detail":"No prompt owner specified"}')
2024-10-31 19:52:51,956 - podcastfy.client - ERROR - An error occurred: Failed to GET /commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc in LangSmith API. HTTPError('400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc', '{"detail":"No prompt owner specified"}')
Traceback (most recent call last):
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\utils.py", line 149, in raise_for_status_with_text
    response.raise_for_status()
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\client.py", line 702, in request_with_retries
    ls_utils.raise_for_status_with_text(response)
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\utils.py", line 151, in raise_for_status_with_text
    raise requests.HTTPError(str(e), response.text) from e  # type: ignore[call-arg]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
requests.exceptions.HTTPError: [Errno 400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc] {"detail":"No prompt owner specified"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Data\Software\Python\Podcastify\app.py", line 51, in <module>
    my_podcast = generate_podcast(urls=urls, conversation_config=podcast_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\podcastfy\client.py", line 307, in generate_podcast
    return process_content(
           ^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\podcastfy\client.py", line 88, in process_content
    qa_content = content_generator.generate_qa_content(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\podcastfy\content_generator.py", line 253, in generate_qa_content
    self.prompt_template, image_path_keys = self.__compose_prompt(num_images)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\podcastfy\content_generator.py", line 90, in __compose_prompt
    prompt_template = hub.pull(
                      ^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langchain\hub.py", line 114, in pull
    response = client.pull_prompt(owner_repo_commit, include_model=include_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\client.py", line 5582, in pull_prompt
    prompt_object = self.pull_prompt_commit(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\client.py", line 5482, in pull_prompt_commit
    response = self.request_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\Software\Python\Podcastify\.venv\Lib\site-packages\langsmith\client.py", line 751, in request_with_retries
    raise ls_utils.LangSmithError(
langsmith.utils.LangSmithError: Failed to GET /commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc in LangSmith API. HTTPError('400 Client Error: Bad Request for url: https://api.smith.langchain.com/commits/-/podcastfy_multimodal_cleanmarkup/3d5b42fc', '{"detail":"No prompt owner specified"}')
PS D:\Data\Software\Python\Podcastify>

**Comment by souzatharsis** [comment]
Thanks, please use the previous version. I am fixing this issue now.
<http://linkedin.com/in/tharsissouza>

**Comment by souzatharsis** [comment]
Google might have updated Gemini today because it's suddenly sending malformed transcripts; tried to fix with prompt but failed. We'll need to add structure output...

**Comment by souzatharsis** [comment]
Issue has been solved is latest release. please update.

thanks for reporting the issue so fast.
