### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by GodAtum360** [souzatharsis/podcastfy#50]
When trying to install (pip install podcastfy) I get the error:

```
     ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"
```

I am running Python 3.13 on Ubuntu 20.

**Comment by souzatharsis** [comment]
That's interesting... This error message suggests that Meson, a build system, is unable to find a C compiler on your system. 

Have you tried:

>    sudo apt update
>    sudo apt install build-essential

**Comment by GodAtum360** [comment]
Thanks, I had to run these:

`sudo apt install build-essential
sudo apt install python-dev
sudo apt-get install python3.13-dev
`

Now when running `python -m podcastfy.client --help`, I get the error:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/christopher/env/lib/python3.13/site-packages/podcastfy/client.py", line 12, in <module>
    from podcastfy.content_generator import ContentGenerator
  File "/home/christopher/env/lib/python3.13/site-packages/podcastfy/content_generator.py", line 13, in <module>
    from langchain_google_genai import ChatGoogleGenerativeAI
  File "/home/christopher/env/lib/python3.13/site-packages/langchain_google_genai/__init__.py", line 58, in <module>
    from langchain_google_genai._enums import HarmBlockThreshold, HarmCategory
  File "/home/christopher/env/lib/python3.13/site-packages/langchain_google_genai/_enums.py", line 1, in <module>
    import google.ai.generativelanguage_v1beta as genai
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/__init__.py", line 21, in <module>
    from .services.cache_service import CacheServiceAsyncClient, CacheServiceClient
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/__init__.py", line 16, in <module>
    from .async_client import CacheServiceAsyncClient
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/async_client.py", line 50, in <module>
    from google.ai.generativelanguage_v1beta.services.cache_service import pagers
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/pagers.py", line 41, in <module>
    from google.ai.generativelanguage_v1beta.types import cache_service, cached_content
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/__init__.py", line 47, in <module>
    from .discuss_service import (
    ...<7 lines>...
    )
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/discuss_service.py", line 22, in <module>
    from google.ai.generativelanguage_v1beta.types import citation, safety
  File "/home/christopher/env/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/safety.py", line 224, in <module>
    class SafetySetting(proto.Message):
    ...<48 lines>...
        )
  File "/home/christopher/env/lib/python3.13/site-packages/proto/message.py", line 279, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/christopher/env/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.ai.generativelanguage.v1beta.__firstlineno__'`

**Comment by souzatharsis** [comment]
This error suggests a conflict in the Google AI Generative Language library. This is likely due to incompatible versions of dependencies or a problem with the installation.

Please try 

`pip install --upgrade google-ai-generativelanguage langchain-google-genai podcastfy`

**Comment by adambwells** [comment]
I also get what looks like an identical error, running Python 3.13 on a Mac (with Sequoia 15.0.1, build 24A348).

```
$ python -m podcastfy.client --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/podcastfy/client.py", line 14, in <module>
    from podcastfy.content_generator import ContentGenerator
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/podcastfy/content_generator.py", line 12, in <module>
    from langchain_google_genai import ChatGoogleGenerativeAI
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/langchain_google_genai/__init__.py", line 58, in <module>
    from langchain_google_genai._enums import HarmBlockThreshold, HarmCategory
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/langchain_google_genai/_enums.py", line 1, in <module>
    import google.ai.generativelanguage_v1beta as genai
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/__init__.py", line 21, in <module>
    from .services.cache_service import CacheServiceAsyncClient, CacheServiceClient
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/__init__.py", line 16, in <module>
    from .async_client import CacheServiceAsyncClient
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/async_client.py", line 50, in <module>
    from google.ai.generativelanguage_v1beta.services.cache_service import pagers
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/services/cache_service/pagers.py", line 41, in <module>
    from google.ai.generativelanguage_v1beta.types import cache_service, cached_content
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/__init__.py", line 47, in <module>
    from .discuss_service import (
    ...<7 lines>...
    )
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/discuss_service.py", line 22, in <module>
    from google.ai.generativelanguage_v1beta.types import citation, safety
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/google/ai/generativelanguage_v1beta/types/safety.py", line 224, in <module>
    class SafetySetting(proto.Message):
    ...<48 lines>...
        )
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/proto/message.py", line 279, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/Development/podcastfy/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.ai.generativelanguage.v1beta.__firstlineno__'
```

I tried upgrading the two modules you mentioned above, but it said that everything was up to date, and the error persists.

**Comment by souzatharsis** [comment]
Thanks for sharing your experience. This further motivates the release of a docker image. There is an already an open issue on it and we should be able to release soon.

**Comment by souzatharsis** [comment]
Hi, Docker image is now available. This should help with compatibility issues regardless of your machine. Please let me know if this issue can be closed.

https://github.com/souzatharsis/podcastfy/blob/main/usage/docker.md

**Comment by souzatharsis** [comment]
I've just made the package docker image public.
Kindly test again and let me know if it works for you.

**Comment by GodAtum360** [comment]
Ran 
```
cd /volume1/docker/podcastfy/
nano .env 
docker pull ghcr.io/souzatharsis/podcastfy:latest
docker-compose up podcastfy
```

But got the error `no configuration file provided: not found`

**Comment by souzatharsis** [comment]
Apologies.

You need a docker-compose.yml file in your /volume1/docker/podcastfy/
directory.

I've now updated documentation to reflect that instruction.

https://github.com/souzatharsis/podcastfy/blob/main/usage/docker.md
<http://linkedin.com/in/tharsissouza>

**Comment by GodAtum360** [comment]
Thjank you, when I run I now get the error:

```
 sudo docker-compose up podcastfy
[+] Running 2/2
 ⠿ Network podcastfy_default        Created                                                                                                  0.5s
 ⠿ Container podcastfy-podcastfy-1  Created                                                                                                  0.2s
Attaching to podcastfy-podcastfy-1
podcastfy-podcastfy-1 exited with code 0
```

**Comment by souzatharsis** [comment]
Hi docker-composer.yml in the docs was incomplete. Updated!

https://github.com/souzatharsis/podcastfy/blob/main/usage/docker.md

**Comment by GodAtum360** [comment]
I now get the error:

`/opt/venv/bin/python3: No module named podcastfy.server`

**Comment by souzatharsis** [comment]
Thank you so much for trying to make it work; I'll replicate the issue locally and get back to you once I am more confident your problem will be solved. Thanks for your patience!

**Comment by adambwells** [comment]
Unfortunately, I still can't get this docker image to work on my M1 MacBook Pro:

`$ docker pull ghcr.io/souzatharsis/podcastfy:latest
Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found`

**Comment by souzatharsis** [comment]
You are right.

We need to build multi-platform images to support ARM64 (M1/M2 Macs). I'll
update the GitHub Actions workflow to build for both amd64 and arm64
architectures.
<http://linkedin.com/in/tharsissouza>

**Comment by verbowersock** [comment]
I cannot run the dev container on Windows 10. I get the error /opt/venv/bin/python3: No module named podcastfy.server

**Comment by GodAtum360** [comment]
> Thank you so much for trying to make it work; I'll replicate the issue locally and get back to you once I am more confident your problem will be solved. Thanks for your patience!

Hi, has the issue been solved now?

**Comment by kemckenz** [comment]
Did support for arm64 ever get added?   I am seeing "Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found".
